### ISSUE TITLE
Tags for ScaLAPACK versions

### ISSUE THREAD

**Issue by zerothi** [Reference-ScaLAPACK/scalapack#13]
I have backtracked the exact commits for the release tars on ScaLAPACK homepage.

It would be nice, for clarity and consistency, to have the tags listed on github as well.

I only took the two most recent ones.

v2.0.2 tar.gz was created from hash: 68165d785dad5f8bd2b87abd091da6cfb86f08d4
v2.0.1 tar.gz was created from hash: d979994d53c204437317e3e9fa9ba69b082d5b4e

Sadly, I cannot create a PR since there are no changes, only tags for commits.
All I did was:
```bash
git tag -a -m "Release 2.0.1" v2.0.1 d979994d53c204437317e3e9fa9ba69b082d5b4e
git tag -a -m "Release 2.0.2" v2.0.2 68165d785dad5f8bd2b87abd091da6cfb86f08d4
git push --tags
```

Thanks!

**Comment by julielangou** [comment]
Sorry for the late handling of this.
Done. Thank you. 
Julie

**Comment by zerothi** [comment]
Thanks!
