### ISSUE TITLE
should SCALAPACK_VERSION be 2.1?

### ISSUE THREAD

**Issue by RizzerOnGitHub** [Reference-ScaLAPACK/scalapack#15]
scalapack 2.1 has just been released.

But CMakeLists.txt line 254 (and following) still sets the version at 2.0.2:

    set(SCALAPACK_VERSION 2.0.2)
    set(CPACK_PACKAGE_VERSION_MAJOR 2)
    set(CPACK_PACKAGE_VERSION_MINOR 0)
    set(CPACK_PACKAGE_VERSION_PATCH 2)

Should these variables have been updated to 2.1?

**Comment by julielangou** [comment]
thanks, had to regenerate the release,.. sorry

**Comment by RizzerOnGitHub** [comment]
Thanks Julie.
