### ISSUE TITLE
ScaLAPACK  fails with GCC 10

### ISSUE THREAD

**Issue by MarcusCalhoun-Lopez** [Reference-ScaLAPACK/scalapack#21]
By default, the about to be released GCC 10  is [more strict about Fortran argument types](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91556).

When attempting to build ScaLAPACK with GCC 10, compiling BLACS code produced many errors of the type
```
Rank mismatch between actual argument at (1) and actual argument at (2)
```

The errors were reduced to warning by adding `-fallow-argument-mismatch` to gfortran.

**Comment by julielangou** [comment]
#26 should fix this issue.
