### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by gdonval** [Reference-ScaLAPACK/scalapack#45]
Trying to compile scalapack with GCC 11.

Same problem as with GCC 10 (https://github.com/Reference-ScaLAPACK/scalapack/issues/21). This was closed a year a half ago but there has been no release since then so the incompatible version is still present everywhere.

Could you consider doing at least a point release, even if just for compatibility?

**Comment by weslleyspereira** [comment]
Hi @gdonval. Thanks for the message! I agree we should have a release with the fixes, and I am currently working on that.

**Comment by weslleyspereira** [comment]
Hi. I marked the current master branch with the tag v2.2.0. We will soon mark it as a release. Thanks again for opening this issue!

**Comment by julielangou** [comment]
Enjoy with moderation ;-)

**Comment by gdonval** [comment]
Brilliant, thanks!
