### ISSUE TITLE
version 2.1 marked in release 2.2 CMakeLists.txt

### ISSUE THREAD

**Issue by drew-parsons** [Reference-ScaLAPACK/scalapack#46]
scalapack 2.2 was recently released.

CMakeLists.txt however still declares
```
set(SCALAPACK_VERSION 2.1.0)
set(CPACK_PACKAGE_VERSION_MAJOR 2)
set(CPACK_PACKAGE_VERSION_MINOR 1)
set(CPACK_PACKAGE_VERSION_PATCH 0)
```
at https://github.com/Reference-ScaLAPACK/scalapack/blob/0128dc24c6d018b61ceaac080640014e1d5ec344/CMakeLists.txt#L258

As a separate suggestion, less characters would need to be updated if the subversions are used:
```
set(CPACK_PACKAGE_VERSION_MAJOR 2)
set(CPACK_PACKAGE_VERSION_MINOR 1)
set(CPACK_PACKAGE_VERSION_PATCH 0)
set(SCALAPACK_VERSION ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH})
```

**Comment by langou** [comment]
Hi @drew-parsons, that's a good idea, thanks for suggesting. Are you interested in providing a PR?, Cheers, @langou

**Comment by drew-parsons** [comment]
I can do a PR.  Before I do that, what's your policy on libscalapack.so, i.e. building a shared library?  Essentially this is a question about your ABI policy.  For Debian, it's convenient to maintain distinct sonames to manage the library when the ABI changes. We've hacked the configration to provide versioned sonames, https://salsa.debian.org/science-team/scalapack/-/blob/master/debian/patches/sharedlibs-soname.patch.

This is done by adding VERSION and/or SOVERSION properties to the scalapack project (in CMakeFiles.txt).  I think it can also be done by declaring `project(SCALAPACK C Fortran)` with a version (`SCALAPACK_VERSION` could be added there).

Is it useful for your shared libraries to be built with a soname?  If so, what ABI compatibility policy does scalapack maintain?

**Comment by weslleyspereira** [comment]
Hi @drew-parsons. Thanks for the suggestions for improvement!

> Or should the PR address only the use of CPACK_PACKAGE_VERSION and not added soname versions?

I think the PR could address sonames. It is a good idea!

Currently, as far as I am aware of, there is no policy implemented for the sonames. Maybe CMake is implementing a default policy, but I am not sure, I have to check. Or maybe you know and an comment on that. This said, would you be able to recommend a policy? Is it a good idea to use `${SCALAPACK_MAJOR_VERSION}.${SCALAPACK_MINOR_VERSION}` for Scalapack as in https://salsa.debian.org/science-team/scalapack/-/blob/master/debian/patches/sharedlibs-soname.patch. Could you please comment on that? Thanks!

**Comment by drew-parsons** [comment]
cmake itself doesn't measure the ABI as such.  It just defines a soname using the VERSION (or SOVERSION) provided to the project.

The ABI would change if there are changes in the internal data structures, e.g. redefining classes using the same name. There is some discussion at https://stackoverflow.com/questions/2171177/what-is-an-application-binary-interface-abi (and a [wiki page](https://en.wikipedia.org/wiki/Application_binary_interface))

If you're changing the API - removing or rearranging function arguments - then it's obvious that the ABI changes.   You would expect that to be the case with a jump in the major version.  If it's just a patch release then that shouldn't really change the ABI (otherwise it's not really a simple patch).

A change in the minor version is a grey area.  Perhaps the fortran argument updates in commit 9c909f0 changes the ABI.

What we've been doing for Debian is to assume the ABI changes with minor version, so we've been using major.minor in the soname.  Perhaps it doesn't always change with every minor release, but better to err on the side of caution.  scalapack does not release new versions too often, so it's no great burden to treat a minor release as an ABI bump.

**Comment by drew-parsons** [comment]
I can prepare a PR. I'll adapt it from the debian patch.  I'll check if the VERSION can go with the project command. The cmake docs seem to indicate that's the place for it.

**Comment by drew-parsons** [comment]
I can prepare a PR. I'll adapt it from the debian patch.  I'll probably put the SCALAPACK_VERSION with the project command. The cmake docs seem to indicate that's the place for it.
