### ISSUE TITLE
tests fail to build: mpi library not linked

### ISSUE THREAD

**Issue by drew-parsons** [Reference-ScaLAPACK/scalapack#47]
For the new v2.2.0, the handling of the fortran compiler was changed in commit [#61c60f5](https://github.com/Reference-ScaLAPACK/scalapack/commit/61c60f570666d5324d086dec37287ffe920e115d) to keep the identity of the fortran compiler (`CMAKE_Fortran_COMPILER`) separate from the MPI fortran compiler (`MPI_Fortran_COMPILER`).  Previously the mpi wrapper was also used as the plain fortran compiler.

That change makes sense. The serial and mpi variants of the fortran compiler should be handled separately. But it has a consequence on the tests in TESTING.  These tests link against `-lscalapack`, but libscalapack requires libmpi. It's not automatically pulled in, the `-lmpi` need to be added when compiling the tests.

The tests are currently configured to use the standard compiler (implicitly, CMAKE_Fortran_COMPILER).  Before commit #61c60f5, the identification with MPI_Fortran_COMPILER meant that mpifort added the required `-lmpi`.  Now that CMAKE_Fortran_COMPILER is kept separate, gfortran is used without `-lmpi`, so tests fail to link, giving errors like (in the case of xclu from TESTING/LIN)
```
/usr/bin/gfortran -Wl,-z,relro -Wl,--as-needed -g -O2 -ffile-prefix-map=/build/scalapack-2.2.0=. -fstack-protector-strong -std=legacy -std=legacy CMakeFiles/xclu.dir/pcludriver.f.o CMakeFiles/xclu.dir/pcluinfo.f.o CMakeFiles/xclu.dir/pcgetrrv.f.o CMakeFiles/xclu.dir/pcmatgen.f.o CMakeFiles/xclu.dir/pmatgeninc.f.o CMakeFiles/xclu.dir/pclaschk.f.o CMakeFiles/xclu.dir/pclafchk.f.o -o ../xclu  -Wl,-rpath,/build/scalapack-2.2.0/build-mpich/lib ../../lib/libscalapack-mpich.so.2.2.0 /usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/x86_64-linux-gnu/libblas.so /usr/lib/x86_64-linux-gnu/libblas.so 
/usr/bin/ld: ../../lib/libscalapack-mpich.so.2.2.0: undefined reference to `MPI_Barrier'
/usr/bin/ld: ../../lib/libscalapack-mpich.so.2.2.0: undefined reference to `MPI_Waitall'
/usr/bin/ld: ../../lib/libscalapack-mpich.so.2.2.0: undefined reference to `MPI_Send'
/usr/bin/ld: ../../lib/libscalapack-mpich.so.2.2.0: undefined reference to `MPI_Comm_dup'
/usr/bin/ld: ../../lib/libscalapack-mpich.so.2.2.0: undefined reference to `MPI_Irecv'
/usr/bin/ld: ../../lib/libscalapack-mpich.so.2.2.0: undefined reference to `MPI_Isend'
...
collect2: error: ld returned 1 exit status
make[4]: *** [TESTING/LIN/CMakeFiles/xclu.dir/build.make:193: TESTING/xclu] Error 1
```

I guess the test configuration should be updated so that the tests get compiled using `MPI_Fortran_COMPILER`

**Comment by drew-parsons** [comment]
Worth noting that C compiler is reset to the MPI wrapper,
https://github.com/Reference-ScaLAPACK/scalapack/blob/0128dc24c6d018b61ceaac080640014e1d5ec344/CMakeLists.txt#L42

So commit [#61c60f5](https://github.com/Reference-ScaLAPACK/scalapack/commit/61c60f570666d5324d086dec37287ffe920e115d) (i.e. PR #39 ) makes the handling of fortran discrepant to the handling of C.

**Comment by weslleyspereira** [comment]
Hi @drew-parsons. Let me ask on #39.

**Comment by ajaypanyala** [comment]
Hi @weslleyspereira Sorry, I overlooked the C compiler line being reset to the MPI wrapper. That can be commented too to make it consistent with commit [#61c60f5](https://github.com/Reference-ScaLAPACK/scalapack/commit/61c60f570666d5324d086dec37287ffe920e115d) and update the test configuration as @drew-parsons suggested. I think the fix here is to simply add `${MPI_Fortran_LIBRARIES}` to each of the `target_link_libraries` line in `TESTING/LIN/CMakeLists.txt`.
