### ISSUE TITLE
Documentation does not notify of github page

### ISSUE THREAD

**Issue by zerothi** [Reference-ScaLAPACK/scalapack#8]
It seems http://www.netlib.org/scalapack/ does not advertise the new repository place?

I think many communities using ScaLAPACK have really wanted a good, common place to put/report bugs/request.

This would be very welcome! :)

PS. Great job on moving it here!!! Much appreciated!

**Comment by julielangou** [comment]
Yes I know, we will wait until the next release I think.. but maybe you are right, nothing is preventing us from doing it right now.

**Comment by zerothi** [comment]
I really think it should be there *now*.

If one searches (on google):
`github scalapack`

this repo isn't to be found on the first page of 10 results. So if we can redirect all development to this repo it would be much better. :)

**Comment by julielangou** [comment]
Updated!
